services:
  consul1:
    image: hashicorp/consul:1.21.1
    ports:
      - "18500:8500"
    command: >
      agent
      -server
      -ui
      -bootstrap-expect=3
      -node=consul1
      -client=0.0.0.0
      -dns-port=0
      -data-dir=/consul/data
      -retry-join=consul2
      -retry-join=consul3
    volumes:
      - ./data/consul1:/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  consul2:
    image: hashicorp/consul:1.21.1
    ports:
      - "18501:8500"
    command: >
      agent
      -server
      -ui
      -bootstrap-expect=3
      -node=consul2
      -client=0.0.0.0
      -dns-port=0
      -data-dir=/consul/data
      -retry-join=consul1
      -retry-join=consul3
    volumes:
      - ./data/consul2:/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  consul3:
    image: hashicorp/consul:1.21.1
    ports:
      - "18502:8500"
    command: >
      agent
      -server
      -ui
      -bootstrap-expect=3
      -node=consul3
      -client=0.0.0.0
      -dns-port=0
      -data-dir=/consul/data
      -retry-join=consul1
      -retry-join=consul2
    volumes:
      - ./data/consul3:/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx1:
    image: nginx:1.27.5
    ports:
      - "80:80"
    environment:
      - SERVICE_NAME=nginx
      - INTERNAL_SERVICE_NAME=nginx1
      - SERVICE_PORT=80
    command: ["/bin/bash", "-c", "chmod +x /register_nginx.sh && /register_nginx.sh"]
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./register_nginx.sh:/register_nginx.sh
    restart: unless-stopped
    depends_on:
      consul1:
        condition: service_healthy
      consul2:
        condition: service_healthy
      consul3:
        condition: service_healthy

  nginx2:
    image: nginx:1.27.5
    ports:
      - "81:80"
    environment:
      - SERVICE_NAME=nginx
      - INTERNAL_SERVICE_NAME=nginx2
      - SERVICE_PORT=81
    command: ["/bin/bash", "-c", "chmod +x /register_nginx.sh && /register_nginx.sh"]
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./register_nginx.sh:/register_nginx.sh
    restart: unless-stopped
    depends_on:
      consul1:
        condition: service_healthy
      consul2:
        condition: service_healthy
      consul3:
        condition: service_healthy
