services:
  mysql-source:
    image: mysql:8.0.40
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-udev_user", "-pdev_password" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: messagesystem
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql-source:/var/lib/mysql
      - ./init-scripts-source:/docker-entrypoint-initdb.d
    command: >
      --server-id=1
      --log_bin=/var/lib/mysql/mysql-bin.log
      --binlog-format=ROW
      --enforce-gtid-consistency=ON
      --gtid-mode=ON

  mysql-replica:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "13307:3306"
    volumes:
      - ./data/mysql-replica:/var/lib/mysql
      - ./init-scripts-replica:/docker-entrypoint-initdb.d
    depends_on:
      mysql-source:
        condition: service_healthy
    command: >
      --server-id=2
      --relay_log=/var/lib/mysql/mysql-relay-bin.log
      --read_only=1
      --enforce-gtid-consistency=ON
      --gtid-mode=ON

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis:/data
  
  redis-insight:
    image: redis/redisinsight:2.64.1
    restart: unless-stopped
    ports:
      - "15540:5540"
    volumes:
      - ./data/redis-insight:/data
